# Generated by Django 4.1.5 on 2023-04-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
